import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1568, height: 941 } });
await page.goto('http://127.0.0.1:27391/', { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
await page.screenshot({ path: 'j:/PigeonYang/WeMediaBuddy/tmp-today-1568.png', fullPage: false });
console.log('screenshot done');
const html = await page.evaluate(() => document.documentElement.outerHTML.slice(0,20000));
console.log(html.slice(0,5000));
await browser.close();
