import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('Discover shows content while Settings owns channel configuration', async () => {
  const discover = await readFile(new URL('../src/renderer/discover-view.tsx', import.meta.url), 'utf8');
  const listContent = await readFile(new URL('../src/renderer/x-lists-view.tsx', import.meta.url), 'utf8');
  const settings = await readFile(new URL('../src/renderer/settings-view.tsx', import.meta.url), 'utf8');
  const listSettings = await readFile(new URL('../src/renderer/x-list-display-settings.tsx', import.meta.url), 'utf8');
  const main = await readFile(new URL('../src/renderer/main.tsx', import.meta.url), 'utf8');
  const piDock = await readFile(new URL('../src/renderer/pi-dock.tsx', import.meta.url), 'utf8');
  const operationModal = await readFile(new URL('../src/renderer/x-list-operation-modal.tsx', import.meta.url), 'utf8');
  const ipc = await readFile(new URL('../src/main/ipc-x-lists.ts', import.meta.url), 'utf8');
  const prd = await readFile(new URL('../PRD.md', import.meta.url), 'utf8');
  const spec = await readFile(new URL('../SPEC.md', import.meta.url), 'utf8');
  assert.doesNotMatch(discover, /IntelligenceChannelsView|情报渠道|List 管理/);
  assert.match(discover, /rankingsEnabled \? \([\s\S]*?role="navigation" aria-label="发现内容"[\s\S]*?AI 榜单[\s\S]*?X Lists/);
  assert.match(discover, /!rankingsEnabled && section === 'rankings' \? 'lists'/);
  assert.match(settings, /section === 'channels'[\s\S]*?<IntelligenceChannelsView settingsMode/);
  assert.doesNotMatch(listContent, /XListComposer|XListConfirmation|接入今日情报|移出今日情报|最终确认并执行|操作记录/);
  assert.match(listSettings, /prepareXListOperation/);
  assert.doesNotMatch(listSettings, /confirmXListOperation|最终确认并执行|读取最新快照/);
  assert.match(listSettings, /setXListBindingEnabled|bindXList/);
  assert.match(listSettings, /操作记录/);
  assert.doesNotMatch(listSettings, /Promise\.all\(\[\s*window\.wmb\.listXListBindings/);
  assert.match(listSettings, /nextOperations\[0\] \?\? null/);
  assert.doesNotMatch(piDock, /XListOperationModal|confirmXListOperation/);
  assert.match(main, /XListOperationModal/);
  assert.match(operationModal, /confirmXListOperation/);
  assert.match(operationModal, /确认执行/);
  assert.doesNotMatch(operationModal, /确认并交给 Pi 执行/);
  assert.match(ipc, /x-lists:confirm[\s\S]*currentXListContext[\s\S]*dispatchAcceptXListOperation/);
  assert.match(ipc, /void runAcceptedXListOperation/);
  assert.match(prd, /Discover 不包含来源配置，只呈现榜单、所选 List 动态/);
  assert.match(spec, /Discover is a content-discovery surface/);
});
