import { mkdtemp, rm } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path';
import { migrateDatabase } from '../src/main/db/migrations.ts';
import { createContentProject, saveCoreVersion, savePlatformVersion } from '../src/main/content.ts';
import { saveAccount } from '../src/main/accounts.ts';
import { createPublication, createPublicationAttempt, reconcileAsNotPublished, recordReconciliation, recoverInterruptedPublications, transitionPublication } from '../src/main/publishing.ts';

const directory = await mkdtemp(path.join(os.tmpdir(), 'wmb-publishing-'));
try {
  const db = migrateDatabase(path.join(directory, 'wmb.db'));
  const project = createContentProject(db, { title: 'publish state' });
  const core = saveCoreVersion(db, project.id, 'core');
  const version = savePlatformVersion(db, { projectId: project.id, contentVersionId: core.id, platform: 'x', format: 'text', body: 'hello' });
  const account = saveAccount(db, { platform: 'x', accountKey: '@owner', displayName: 'Owner', loginState: 'authenticated', evidenceUrl: 'https://x.com/owner' });
  if (!version.ok) throw new Error('version setup failed');
  const created = createPublication(db, { platformVersionId: version.data.id, accountId: account.id });
  if (!created.ok || created.data.status !== 'draft') throw new Error('draft creation failed');
  const invalid = transitionPublication(db, created.data.id, 'published', { expectedRevision: 1, externalUrl: 'https://x.com/owner/status/1', externalId: '1' });
  if (invalid.ok || invalid.error.code !== 'INVALID_STATE') throw new Error('invalid transition accepted');
  const prepared = transitionPublication(db, created.data.id, 'prepared', { expectedRevision: 1 });
  const awaiting = prepared.ok && transitionPublication(db, created.data.id, 'awaiting_confirmation', { expectedRevision: prepared.data.revision });
  const publishing = awaiting && awaiting.ok && transitionPublication(db, created.data.id, 'publishing', { expectedRevision: awaiting.data.revision });
  if (!publishing || !publishing.ok) throw new Error('publishing transition failed');
  const attempt = createPublicationAttempt(db, created.data.id);
  if (!attempt.ok || attempt.data.attemptNumber !== 1) throw new Error('attempt creation failed');
  const unknown = transitionPublication(db, created.data.id, 'unknown', { expectedRevision: publishing.data.revision, reason: 'readback interrupted' });
  if (!unknown.ok) throw new Error('unknown transition failed');
  const reconciliation = recordReconciliation(db, { publicationId: created.data.id, attemptId: attempt.data.id, outcome: 'ambiguous', evidence: { candidates: 2 } });
  if (!reconciliation.ok) throw new Error('reconciliation persistence failed');
  const stillUnknown = db.prepare('SELECT status FROM publications WHERE id = ?').get(created.data.id);
  const attemptState = db.prepare('SELECT status, finished_at AS finishedAt FROM publication_attempts WHERE id = ?').get(attempt.data.id);
  const evidence = db.prepare('SELECT evidence_json AS evidence FROM publication_reconciliations WHERE id = ?').get(reconciliation.data.id);
  if (stillUnknown.status !== 'unknown' || attemptState.status !== 'unknown' || !attemptState.finishedAt || JSON.parse(evidence.evidence).candidates !== 2) throw new Error('unknown evidence mismatch');
  const published = transitionPublication(db, created.data.id, 'published', { expectedRevision: unknown.data.revision, externalUrl: 'https://x.com/owner/status/1', externalId: '1' });
  const terminal = published.ok && transitionPublication(db, created.data.id, 'failed', { expectedRevision: published.data.revision });
  if (!published.ok || !terminal || terminal.ok || terminal.error.code !== 'INVALID_STATE') throw new Error('terminal state mismatch');
  const second = createPublication(db, { platformVersionId: version.data.id, accountId: account.id });
  if (!second.ok) throw new Error('second publication setup failed');
  const secondPrepared = transitionPublication(db, second.data.id, 'prepared', { expectedRevision: 1 });
  const secondAwaiting = secondPrepared.ok && transitionPublication(db, second.data.id, 'awaiting_confirmation', { expectedRevision: secondPrepared.data.revision });
  const secondPublishing = secondAwaiting && secondAwaiting.ok && transitionPublication(db, second.data.id, 'publishing', { expectedRevision: secondAwaiting.data.revision });
  if (!secondPublishing || !secondPublishing.ok) throw new Error('second publishing setup failed');
  const secondAttempt = createPublicationAttempt(db, second.data.id);
  const secondUnknown = secondAttempt.ok && transitionPublication(db, second.data.id, 'unknown', { expectedRevision: secondPublishing.data.revision });
  const resolved = secondUnknown && secondUnknown.ok && reconcileAsNotPublished(db, { publicationId: second.data.id, expectedRevision: secondUnknown.data.revision, evidence: { checked: true } });
  if (!resolved || !resolved.ok || resolved.data.status !== 'failed' || db.prepare('SELECT COUNT(*) AS count FROM publication_attempts WHERE publication_id = ?').get(second.data.id).count !== 1) throw new Error('controlled unknown reconciliation retried publication');
  const events = db.prepare('SELECT COUNT(*) AS count FROM publication_events WHERE publication_id = ?').get(created.data.id);
  if (events.count !== 6) throw new Error(`event timeline mismatch: ${events.count}`);
  const interrupted = createPublication(db, { platformVersionId: version.data.id, accountId: account.id });
  const interruptedPrepared = interrupted.ok && transitionPublication(db, interrupted.data.id, 'prepared', { expectedRevision: interrupted.data.revision });
  const interruptedAwaiting = interruptedPrepared && interruptedPrepared.ok && transitionPublication(db, interrupted.data.id, 'awaiting_confirmation', { expectedRevision: interruptedPrepared.data.revision });
  const interruptedPublishing = interruptedAwaiting && interruptedAwaiting.ok && transitionPublication(db, interrupted.data.id, 'publishing', { expectedRevision: interruptedAwaiting.data.revision });
  if (!interruptedPublishing || !interruptedPublishing.ok || !createPublicationAttempt(db, interrupted.data.id).ok) throw new Error('interrupted publication setup failed');
  db.close();
  const reopened = migrateDatabase(path.join(directory, 'wmb.db'));
  recoverInterruptedPublications(reopened);
  const recovered = reopened.prepare('SELECT status, revision FROM publications WHERE id = ?').get(interrupted.data.id);
  const recoveredAttempt = reopened.prepare('SELECT status, error_code AS errorCode FROM publication_attempts WHERE publication_id = ?').get(interrupted.data.id);
  if (recovered.status !== 'unknown' || recoveredAttempt.status !== 'unknown' || recoveredAttempt.errorCode !== 'PUBLICATION_UNKNOWN') throw new Error('restart did not preserve publication uncertainty');
  const recoveredRevision = recovered.revision;
  recoverInterruptedPublications(reopened);
  if (reopened.prepare('SELECT revision FROM publications WHERE id = ?').get(interrupted.data.id).revision !== recoveredRevision) throw new Error('restart recovery was not idempotent');
  reopened.close();
} finally { await rm(directory, { recursive: true, force: true, maxRetries: 3, retryDelay: 100 }); }
