import { randomUUID } from 'node:crypto';
import type { DatabaseSync } from 'node:sqlite';
import { fingerprintTopic } from './ferment.ts';
import { buildTopicConflictContract, evaluateTopicConflictContract, type TopicConflictContractV2, type TopicConflictEvidence } from './topic-maintenance-conflict.ts';
import { completeTopicReproposal, enqueueTopicReproposal, getTopicReproposal } from './topic-maintenance-reproposal.ts';
import { recordTopicProposalUsage } from './knowledge-usage-integration.ts';

export type TopicMaintenanceChange =
  | { kind: 'create'; topicId?: string; after: TopicDraft }
  | { kind: 'update'; topicId: string; after: TopicDraft }
  | { kind: 'merge'; retainedTopicId: string; mergedTopicId: string }
  | { kind: 'archive'; topicId: string }
  | { kind: 'reassign'; sourceId: string; fromTopicId: string; toTopicId: string; relation?: string };
export type TopicDraft = { title: string; canonicalKey?: string; kind?: 'theme' | 'event'; summary?: string | null; status?: 'active' | 'watching' | 'dormant' | 'archived' };
type ProposalRow = { id: string; task_id: string | null; supersedes_proposal_id: string | null; title: string; reason: string; changes_json: string; expected_json: string; stale_reason_json: string | null; status: string; revision: number; created_at: string; updated_at: string; decided_at: string | null };
type RecordRow = Record<string, unknown>;
type TopicSnapshot = { version: 1 | 2; frozenAt: string; before: SnapshotState; after: SnapshotState; counts: Record<string, number>; conflictContract?: TopicConflictContractV2 };
type SnapshotState = { topics: RecordRow[]; absentCanonicalKeys: string[]; sourceLinks: RecordRow[]; planItems: RecordRow[]; contentProjects: RecordRow[]; workCarryItems: RecordRow[]; knowledgeCanvases: RecordRow[]; knowledgeCanvasNodes: RecordRow[]; knowledgeDomainTopics: RecordRow[]; reviews: RecordRow[] };

const TABLES = ['sourceLinks', 'planItems', 'contentProjects', 'workCarryItems', 'knowledgeCanvases', 'knowledgeCanvasNodes', 'knowledgeDomainTopics', 'reviews'] as const;
const emptyState = (): SnapshotState => ({ topics: [], absentCanonicalKeys: [], sourceLinks: [], planItems: [], contentProjects: [], workCarryItems: [], knowledgeCanvases: [], knowledgeCanvasNodes: [], knowledgeDomainTopics: [], reviews: [] });
const key = (row: RecordRow) => JSON.stringify(row);
const normalizedRows = (rows: RecordRow[]) => rows.map((row) => Object.fromEntries(Object.entries(row).sort(([a], [b]) => a.localeCompare(b)))).sort((a, b) => key(a).localeCompare(key(b)));
const normalKey = (value: string) => value.trim().toLocaleLowerCase();
const asRows = (database: DatabaseSync, sql: string, ...params: unknown[]) => normalizedRows(database.prepare(sql).all(...params as any[]) as RecordRow[]);
const parse = (database: DatabaseSync, row: ProposalRow) => ({ id: row.id, taskId: row.task_id, supersedesProposalId: row.supersedes_proposal_id, title: row.title, reason: row.reason, changes: JSON.parse(row.changes_json) as TopicMaintenanceChange[], snapshot: JSON.parse(row.expected_json) as TopicSnapshot, staleReason: row.stale_reason_json ? JSON.parse(row.stale_reason_json) as TopicConflictEvidence[] : null, reproposal: getTopicReproposal(database, row.id), status: row.status, revision: row.revision, createdAt: row.created_at, updatedAt: row.updated_at, decidedAt: row.decided_at });
export type TopicMaintenanceProposal = ReturnType<typeof parse>;
function topic(database: DatabaseSync, id: string): RecordRow { const row = database.prepare('SELECT * FROM topics WHERE id=?').get(id) as RecordRow | undefined; if (!row) throw new Error('TOPIC_NOT_FOUND'); return row; }
function source(database: DatabaseSync, id: string): void { if (!database.prepare('SELECT id FROM source_items WHERE id=?').get(id)) throw new Error('SOURCE_ITEMS_NOT_FOUND'); }

function relationState(database: DatabaseSync, topicIds: readonly string[], sourceIds: readonly string[]): Omit<SnapshotState, 'topics' | 'absentCanonicalKeys'> {
  const state = emptyState(); const placeholders = (ids: readonly string[]) => ids.map(() => '?').join(',');
  if (topicIds.length) {
    const q = placeholders(topicIds);
    state.sourceLinks = asRows(database, `SELECT * FROM topic_source_links WHERE topic_id IN (${q})`, ...topicIds);
    state.planItems = asRows(database, `SELECT * FROM plan_items WHERE topic_id IN (${q})`, ...topicIds);
    state.contentProjects = asRows(database, `SELECT * FROM content_projects WHERE topic_id IN (${q})`, ...topicIds);
    state.workCarryItems = asRows(database, `SELECT * FROM work_carry_items WHERE topic_id IN (${q}) OR (object_type='topic' AND object_id IN (${q}))`, ...topicIds, ...topicIds);
    state.knowledgeCanvases = asRows(database, `SELECT * FROM knowledge_canvases WHERE topic_id IN (${q})`, ...topicIds);
    state.knowledgeCanvasNodes = asRows(database, `SELECT * FROM knowledge_canvas_nodes WHERE object_type='topic' AND object_id IN (${q})`, ...topicIds);
    state.knowledgeDomainTopics = asRows(database, `SELECT * FROM knowledge_domain_topics WHERE topic_id IN (${q})`, ...topicIds);
    state.reviews = asRows(database, `SELECT r.id AS review_id,r.revision AS review_revision,r.content_version_id,p.id AS publication_id,pv.id AS platform_version_id,pv.project_id,cp.topic_id FROM reviews r JOIN publications p ON p.id=r.publication_id JOIN platform_versions pv ON pv.id=p.platform_version_id JOIN content_projects cp ON cp.id=pv.project_id WHERE cp.topic_id IN (${q})`, ...topicIds);
  }
  if (sourceIds.length) {
    const rows = asRows(database, `SELECT * FROM topic_source_links WHERE source_id IN (${placeholders(sourceIds)})`, ...sourceIds);
    state.sourceLinks = normalizedRows([...state.sourceLinks, ...rows].filter((row, index, list) => list.findIndex((item) => key(item) === key(row)) === index));
  }
  return state;
}
function snapshotState(database: DatabaseSync, changes: readonly TopicMaintenanceChange[]): SnapshotState {
  const ids = new Set<string>(), sources = new Set<string>(), absent = new Set<string>();
  for (const change of changes) {
    if (change.kind === 'create') absent.add(normalKey(change.after.canonicalKey ?? change.after.title));
    if (change.kind === 'update' || change.kind === 'archive') ids.add(change.topicId);
    if (change.kind === 'merge') { ids.add(change.retainedTopicId); ids.add(change.mergedTopicId); }
    if (change.kind === 'reassign') { ids.add(change.fromTopicId); ids.add(change.toTopicId); sources.add(change.sourceId); }
  }
  const topicIds = [...ids].sort(), sourceIds = [...sources].sort();
  const relations = relationState(database, topicIds, sourceIds);
  return { ...relations, topics: normalizedRows(topicIds.map((id) => topic(database, id))), absentCanonicalKeys: [...absent].sort() };
}
function predictedState(before: SnapshotState, changes: readonly TopicMaintenanceChange[], frozenAt: string): SnapshotState {
  const after: SnapshotState = JSON.parse(JSON.stringify(before));
  for (const change of changes) {
    if (change.kind === 'create') after.topics.push({ id: change.topicId!, title: change.after.title.trim(), canonical_key: normalKey(change.after.canonicalKey ?? change.after.title), kind: change.after.kind ?? 'theme', summary: change.after.summary ?? null, status: change.after.status ?? 'active', created_at: frozenAt, updated_at: frozenAt, revision: 1, first_seen_at: frozenAt, last_seen_at: frozenAt });
    if (change.kind === 'update') after.topics = after.topics.map((row) => String(row.id) === change.topicId ? { ...row, title: change.after.title.trim(), canonical_key: normalKey(change.after.canonicalKey ?? change.after.title), kind: change.after.kind ?? 'theme', summary: change.after.summary ?? null, status: change.after.status ?? 'active', updated_at: frozenAt, last_seen_at: frozenAt, revision: Number(row.revision) + 1 } : row);
    if (change.kind === 'archive') after.topics = after.topics.map((row) => String(row.id) === change.topicId ? { ...row, status: 'archived', updated_at: frozenAt, revision: Number(row.revision) + 1 } : row);
    if (change.kind === 'merge') {
      after.topics = after.topics.map((row) => String(row.id) === change.mergedTopicId ? { ...row, status: 'archived', updated_at: frozenAt, revision: Number(row.revision) + 1 } : row);
      for (const field of ['sourceLinks', 'planItems', 'contentProjects', 'knowledgeCanvases', 'knowledgeCanvasNodes', 'knowledgeDomainTopics'] as const) after[field] = after[field].map((row) => moveTopicRow(field, row, change.mergedTopicId, change.retainedTopicId, frozenAt));
      after.workCarryItems = moveWorkCarryRows(after.workCarryItems, change.mergedTopicId, change.retainedTopicId, frozenAt);
      after.reviews = after.reviews.map((row) => String(row.topic_id) === change.mergedTopicId ? { ...row, topic_id: change.retainedTopicId } : row);
    }
    if (change.kind === 'reassign') after.sourceLinks = after.sourceLinks.map((row) => String(row.topic_id) === change.fromTopicId && String(row.source_id) === change.sourceId && (change.relation === undefined || String(row.relation) === change.relation) ? { ...row, topic_id: change.toTopicId, updated_at: frozenAt } : row);
  }
  after.topics = normalizedRows(after.topics); after.absentCanonicalKeys = after.absentCanonicalKeys.filter((value) => !after.topics.some((row) => row.canonical_key === value));
  for (const field of TABLES) after[field] = normalizedRows(after[field]);
  return after;
}
function moveTopicRow(field: typeof TABLES[number], row: RecordRow, oldId: string, retainedId: string, frozenAt: string): RecordRow {
  if (field === 'knowledgeCanvasNodes') return row.object_type === 'topic' && String(row.object_id) === oldId ? { ...row, object_id: retainedId, updated_at: frozenAt, revision: Number(row.revision) + 1 } : row;
  return String(row.topic_id) === oldId ? { ...row, topic_id: retainedId, ...(field === 'sourceLinks' ? { updated_at: frozenAt } : {}), ...(field === 'planItems' || field === 'contentProjects' || field === 'knowledgeCanvases' ? { updated_at: frozenAt, revision: Number(row.revision) + 1 } : {}) } : row;
}
function moveWorkCarryRows(rows: RecordRow[], oldId: string, retainedId: string, now: string): RecordRow[] { const canonical = fingerprintTopic(retainedId), target = rows.find((row) => row.object_type === 'topic' && String(row.object_id) === retainedId); return rows.map((row) => String(row.topic_id) === oldId || (row.object_type === 'topic' && String(row.object_id) === oldId) ? { ...row, ...(String(row.topic_id) === oldId ? { topic_id: retainedId } : {}), ...(row.object_type === 'topic' && String(row.object_id) === oldId ? { object_id: retainedId, fingerprint: target && target.id !== row.id ? `${canonical}:merged:${String(row.id)}` : canonical, story_key: `topic:${retainedId}` } : {}), updated_at: now, revision: Number(row.revision) + 1 } : row); }
function validate(changes: readonly TopicMaintenanceChange[], database: DatabaseSync): TopicMaintenanceChange[] {
  const seen = new Set<string>(), canonicalKeys = new Set<string>(), reassignedRelations = new Map<string, Set<string>>(), merged = new Map<string, string>(), mutated = new Set<string>();
  const normalized = changes.map((change) => change.kind === 'create' ? { ...change, topicId: change.topicId ?? randomUUID(), after: { ...change.after, title: change.after.title.trim() } } : change) as TopicMaintenanceChange[];
  const mergeTopics = new Set(normalized.flatMap((change) => change.kind === 'merge' ? [change.retainedTopicId, change.mergedTopicId] : []));
  for (const change of normalized) {
    const marker = change.kind === 'merge' ? `merge:${change.mergedTopicId}` : change.kind === 'reassign' ? `reassign:${change.sourceId}:${change.fromTopicId}:${change.toTopicId}:${change.relation ?? ''}` : `${change.kind}:${change.topicId}`;
    if (seen.has(marker)) throw new Error('TOPIC_CHANGE_DUPLICATE'); seen.add(marker);
    if (change.kind === 'create' || change.kind === 'update') { if (!change.after.title) throw new Error('TOPIC_REQUIRED'); const canonicalKey = normalKey(change.after.canonicalKey ?? change.after.title); if (canonicalKeys.has(canonicalKey)) throw new Error('TOPIC_CHANGE_DUPLICATE_CANONICAL'); canonicalKeys.add(canonicalKey); const occupied = database.prepare('SELECT id FROM topics WHERE canonical_key=? AND (? IS NULL OR id<>?)').get(canonicalKey, change.kind === 'update' ? change.topicId : null, change.kind === 'update' ? change.topicId : null); if (occupied) throw new Error('TOPIC_ALREADY_EXISTS'); }
    if (change.kind === 'merge') { if (change.mergedTopicId === change.retainedTopicId) throw new Error('TOPIC_MERGE_SAME'); if (merged.has(change.mergedTopicId)) throw new Error('TOPIC_MERGE_DUPLICATE_SOURCE'); if (mutated.has(change.mergedTopicId) || mutated.has(change.retainedTopicId)) throw new Error('TOPIC_CHANGE_CONTRADICTORY'); const retained = topic(database, change.retainedTopicId); topic(database, change.mergedTopicId); if (retained.status !== 'active') throw new Error('TOPIC_MERGE_TARGET_INACTIVE'); const canvasCollision = database.prepare("SELECT 1 FROM knowledge_canvas_nodes old JOIN knowledge_canvas_nodes retained ON retained.canvas_id=old.canvas_id AND retained.object_type='topic' AND retained.object_id=? WHERE old.object_type='topic' AND old.object_id=? LIMIT 1").get(change.retainedTopicId, change.mergedTopicId); if (canvasCollision) throw new Error('TOPIC_MERGE_CANVAS_COLLISION'); merged.set(change.mergedTopicId, change.retainedTopicId); }
    if (change.kind === 'archive' || change.kind === 'update') { if (mutated.has(change.topicId) || mergeTopics.has(change.topicId)) throw new Error('TOPIC_CHANGE_CONTRADICTORY'); mutated.add(change.topicId); }
    if (change.kind === 'reassign') { if (change.fromTopicId === change.toTopicId) throw new Error('TOPIC_REASSIGN_SAME'); if (mergeTopics.has(change.fromTopicId) || mergeTopics.has(change.toTopicId)) throw new Error('TOPIC_CHANGE_CONTRADICTORY'); topic(database, change.fromTopicId); topic(database, change.toTopicId); source(database, change.sourceId); const relations = (change.relation === undefined ? database.prepare('SELECT relation FROM topic_source_links WHERE topic_id=? AND source_id=?').all(change.fromTopicId, change.sourceId) : database.prepare('SELECT relation FROM topic_source_links WHERE topic_id=? AND source_id=? AND relation=?').all(change.fromTopicId, change.sourceId, change.relation) as Array<{ relation: string }>).map((row) => String(row.relation)); if (!relations.length) throw new Error('TOPIC_REASSIGN_LINK_NOT_FOUND'); const relationKey = `${change.sourceId}:${change.fromTopicId}`, claimed = reassignedRelations.get(relationKey) ?? new Set<string>(); if (relations.some((relation) => claimed.has(relation))) throw new Error('TOPIC_CHANGE_CONTRADICTORY'); relations.forEach((relation) => claimed.add(relation)); reassignedRelations.set(relationKey, claimed); }
  }
  if ([...merged.values()].some((target) => merged.has(target))) throw new Error('TOPIC_MERGE_CHAIN');
  return normalized;
}
function sameState(a: SnapshotState, b: SnapshotState): boolean { return JSON.stringify(a) === JSON.stringify(b); }
function currentMatches(database: DatabaseSync, snapshot: TopicSnapshot, changes: readonly TopicMaintenanceChange[]): boolean {
  if (snapshot.before.absentCanonicalKeys.some((canonicalKey) => database.prepare('SELECT id FROM topics WHERE canonical_key=?').get(canonicalKey))) return false;
  const topicIds = snapshot.before.topics.map((row) => String(row.id)); const sourceIds = [...new Set(changes.flatMap((change) => change.kind === 'reassign' ? [change.sourceId] : []))];
  const current = relationState(database, topicIds, sourceIds); const topics = topicIds.map((id) => database.prepare('SELECT * FROM topics WHERE id=?').get(id)).filter(Boolean) as RecordRow[];
  return topics.length === topicIds.length && sameState(snapshot.before, { ...current, topics: normalizedRows(topics), absentCanonicalKeys: snapshot.before.absentCanonicalKeys });
}
function executeFrozen(database: DatabaseSync, proposal: ReturnType<typeof parse>): void {
  const { changes, snapshot } = proposal; const now = snapshot.frozenAt;
  for (const change of changes) {
    if (change.kind === 'create') database.prepare('INSERT INTO topics(id,title,created_at,updated_at,revision,canonical_key,kind,summary,status,first_seen_at,last_seen_at) VALUES(?,?,?,?,1,?,?,?,?,?,?)').run(change.topicId!, change.after.title.trim(), now, now, normalKey(change.after.canonicalKey ?? change.after.title), change.after.kind ?? 'theme', change.after.summary ?? null, change.after.status ?? 'active', now, now);
    if (change.kind === 'update') database.prepare('UPDATE topics SET title=?,canonical_key=?,kind=?,summary=?,status=?,updated_at=?,last_seen_at=?,revision=revision+1 WHERE id=?').run(change.after.title.trim(), normalKey(change.after.canonicalKey ?? change.after.title), change.after.kind ?? 'theme', change.after.summary ?? null, change.after.status ?? 'active', now, now, change.topicId);
    if (change.kind === 'archive') database.prepare("UPDATE topics SET status='archived',updated_at=?,revision=revision+1 WHERE id=?").run(now, change.topicId);
    if (change.kind === 'reassign') applySourceMove(database, snapshot.before.sourceLinks, change.fromTopicId, change.toTopicId, change.sourceId, change.relation, now);
    if (change.kind === 'merge') { applyMerge(database, snapshot.before, change.mergedTopicId, change.retainedTopicId, now); database.prepare("UPDATE topics SET status='archived',updated_at=?,revision=revision+1 WHERE id=?").run(now, change.mergedTopicId); assertNoFormalReferences(database, change.mergedTopicId); }
  }
}
function applySourceMove(database: DatabaseSync, links: RecordRow[], oldId: string, newId: string, sourceId: string, relation: string | undefined, now: string): void { for (const row of links.filter((row) => String(row.topic_id) === oldId && String(row.source_id) === sourceId && (relation === undefined || String(row.relation) === relation))) { database.prepare('DELETE FROM topic_source_links WHERE topic_id=? AND source_id=? AND relation=?').run(oldId, sourceId, row.relation as any); database.prepare('INSERT OR IGNORE INTO topic_source_links(topic_id,source_id,relation,created_at,updated_at) VALUES(?,?,?,?,?)').run(newId, sourceId, row.relation as any, row.created_at as any, now); } }
function applyMerge(database: DatabaseSync, before: SnapshotState, oldId: string, retainedId: string, now: string): void {
  for (const row of before.sourceLinks.filter((row) => String(row.topic_id) === oldId)) applySourceMove(database, [row], oldId, retainedId, String(row.source_id), String(row.relation), now);
  for (const row of before.planItems.filter((row) => String(row.topic_id) === oldId)) database.prepare('UPDATE plan_items SET topic_id=?,updated_at=?,revision=revision+1 WHERE id=? AND revision=?').run(retainedId, now, row.id as any, row.revision as any);
  for (const row of before.contentProjects.filter((row) => String(row.topic_id) === oldId)) database.prepare('UPDATE content_projects SET topic_id=?,updated_at=?,revision=revision+1 WHERE id=? AND revision=?').run(retainedId, now, row.id as any, row.revision as any);
  const movedCarry = moveWorkCarryRows(before.workCarryItems, oldId, retainedId, now);
  for (const row of movedCarry.filter((row) => before.workCarryItems.some((original) => original.id === row.id && key(original) !== key(row)))) database.prepare('UPDATE work_carry_items SET topic_id=?,object_id=?,fingerprint=?,story_key=?,updated_at=?,revision=? WHERE id=? AND revision=?').run(row.topic_id as any, row.object_id as any, row.fingerprint as any, row.story_key as any, row.updated_at as any, row.revision as any, row.id as any, Number(row.revision) - 1);
  for (const row of before.knowledgeCanvases.filter((row) => String(row.topic_id) === oldId)) database.prepare('UPDATE knowledge_canvases SET topic_id=?,updated_at=?,revision=revision+1 WHERE id=? AND revision=?').run(retainedId, now, row.id as any, row.revision as any);
  for (const row of before.knowledgeCanvasNodes.filter((row) => row.object_type === 'topic' && String(row.object_id) === oldId)) database.prepare('UPDATE knowledge_canvas_nodes SET object_id=?,updated_at=?,revision=revision+1 WHERE id=? AND revision=?').run(retainedId, now, row.id as any, row.revision as any);
  const domainIds = new Set<string>();
  for (const row of before.knowledgeDomainTopics.filter((row) => String(row.topic_id) === oldId)) { database.prepare('DELETE FROM knowledge_domain_topics WHERE domain_id=? AND topic_id=?').run(row.domain_id as any, oldId); database.prepare('INSERT OR IGNORE INTO knowledge_domain_topics(domain_id,topic_id,sort_order,added_at) VALUES(?,?,?,?)').run(row.domain_id as any, retainedId, row.sort_order as any, row.added_at as any); domainIds.add(String(row.domain_id)); }
  for (const domainId of domainIds) database.prepare('UPDATE knowledge_domains SET updated_at=?,revision=revision+1 WHERE id=?').run(now, domainId);
}
function assertNoFormalReferences(database: DatabaseSync, topicId: string): void { const count = Number((database.prepare("SELECT (SELECT count(*) FROM topic_source_links WHERE topic_id=?) + (SELECT count(*) FROM plan_items WHERE topic_id=?) + (SELECT count(*) FROM content_projects WHERE topic_id=?) + (SELECT count(*) FROM work_carry_items WHERE topic_id=? OR (object_type='topic' AND object_id=?)) + (SELECT count(*) FROM knowledge_canvases WHERE topic_id=?) + (SELECT count(*) FROM knowledge_canvas_nodes WHERE object_type='topic' AND object_id=?) + (SELECT count(*) FROM knowledge_domain_topics WHERE topic_id=?) AS count").get(topicId, topicId, topicId, topicId, topicId, topicId, topicId, topicId) as { count: number }).count); if (count) throw new Error('TOPIC_MERGE_REFERENCES_REMAIN'); }

/** Creates a fully frozen proposal; no formal topic relation is written. */
export function createTopicMaintenanceProposal(database: DatabaseSync, input: { taskId?: string; supersedesProposalId?: string; title: string; reason: string; changes: TopicMaintenanceChange[] }) { if (input.supersedesProposalId) { const existing = database.prepare('SELECT * FROM topic_maintenance_proposals WHERE supersedes_proposal_id=?').get(input.supersedesProposalId) as ProposalRow | undefined; if (existing) return parse(database, existing); const parent = getTopicMaintenanceProposal(database, input.supersedesProposalId); if (!parent || parent.status !== 'stale' || !parent.reproposal || !['pending', 'needs_user'].includes(parent.reproposal.status)) throw new Error('TOPIC_REPROPOSAL_PARENT_INVALID'); } const title = input.title.trim(), reason = input.reason.trim(); if (!title || !reason || !input.changes.length) throw new Error('TOPIC_PROPOSAL_REQUIRED'); const changes = validate(input.changes, database); const frozenAt = new Date().toISOString(), before = snapshotState(database, changes), snapshot: TopicSnapshot = { version: 2, frozenAt, before, after: predictedState(before, changes, frozenAt), counts: Object.fromEntries(TABLES.map((field) => [field, before[field].length])), conflictContract: buildTopicConflictContract(database, changes) }; const id = randomUUID(); database.prepare("INSERT INTO topic_maintenance_proposals(id,task_id,supersedes_proposal_id,title,reason,changes_json,expected_json,status,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?, 'proposed',1,?,?)").run(id, input.taskId ?? null, input.supersedesProposalId ?? null, title, reason, JSON.stringify(changes), JSON.stringify(snapshot), frozenAt, frozenAt); if (input.supersedesProposalId) completeTopicReproposal(database, input.supersedesProposalId, id, frozenAt); { const affectedTopicIds = [...new Set(changes.flatMap((change) => { if (change.kind === 'update' || change.kind === 'archive') return [change.topicId]; if (change.kind === 'merge') return [change.retainedTopicId, change.mergedTopicId]; if (change.kind === 'reassign') return [change.fromTopicId, change.toTopicId]; return []; }))]; recordTopicProposalUsage(database, { proposalId: id, topicIds: affectedTopicIds, reason: `topic_proposal:${title}` }); } return getTopicMaintenanceProposal(database, id)!; }
export function getTopicMaintenanceProposal(database: DatabaseSync, id: string) { const row = database.prepare('SELECT * FROM topic_maintenance_proposals WHERE id=?').get(id) as ProposalRow | undefined; return row ? parse(database, row) : null; }
export function listTopicMaintenanceProposals(database: DatabaseSync, input: { status?: string; limit?: number; offset?: number } = {}) { const limit = Math.min(Math.max(input.limit ?? 50, 1), 100), offset = Math.max(input.offset ?? 0, 0), status = input.status ?? ''; const total = Number((database.prepare("SELECT count(*) AS count FROM topic_maintenance_proposals WHERE (?='' OR status=?)").get(status, status) as { count: number }).count); const items = (database.prepare("SELECT * FROM topic_maintenance_proposals WHERE (?='' OR status=?) ORDER BY created_at DESC,id DESC LIMIT ? OFFSET ?").all(status, status, limit, offset) as ProposalRow[]).map((row) => parse(database, row)); return { items, total, limit, offset, hasMore: offset + items.length < total }; }
export function readLatestTopicMaintenanceProposalForTask(database: DatabaseSync, taskId: string, sinceIso: string): TopicMaintenanceProposal | null { const row = database.prepare(`SELECT result_json AS resultJson FROM command_receipts WHERE task_id=? AND status='ok' AND command='knowledge.topic_maintenance_propose' AND created_at>=? ORDER BY created_at DESC LIMIT 1`).get(taskId, sinceIso) as { resultJson: string | null } | undefined; return row?.resultJson ? JSON.parse(row.resultJson) as TopicMaintenanceProposal : null; }
/** Owner decision. Every business write is inside the caller transaction/savepoint and only uses frozen rows. */
export function decideTopicMaintenanceProposal(database: DatabaseSync, input: { id: string; expectedRevision: number; decision: 'approve' | 'reject' }) { const proposal = getTopicMaintenanceProposal(database, input.id); if (!proposal) throw new Error('TOPIC_PROPOSAL_NOT_FOUND'); if (proposal.revision !== input.expectedRevision) throw new Error('REVISION_CONFLICT'); if (proposal.status !== 'proposed') throw new Error('TOPIC_PROPOSAL_NOT_PENDING'); const now = new Date().toISOString(); if (input.decision === 'reject') { database.prepare("UPDATE topic_maintenance_proposals SET status='rejected',revision=revision+1,updated_at=?,decided_at=? WHERE id=?").run(now, now, input.id); return getTopicMaintenanceProposal(database, input.id)!; } const isV2 = proposal.snapshot.version === 2 && proposal.snapshot.conflictContract; const conflicts: TopicConflictEvidence[] = isV2 ? evaluateTopicConflictContract(database, proposal.snapshot.conflictContract!) : currentMatches(database, proposal.snapshot, proposal.changes) ? [] : [{ kind: 'legacy_snapshot', identity: proposal.id, expected: 'frozen', actual: 'changed' }]; if (conflicts.length) { database.exec('SAVEPOINT topic_maintenance_stale'); try { database.prepare("UPDATE topic_maintenance_proposals SET status='stale',stale_reason_json=?,revision=revision+1,updated_at=?,decided_at=? WHERE id=?").run(JSON.stringify(conflicts), now, now, input.id); if (isV2) enqueueTopicReproposal(database, input.id, conflicts, now); database.exec('RELEASE topic_maintenance_stale'); } catch (error) { database.exec('ROLLBACK TO topic_maintenance_stale'); database.exec('RELEASE topic_maintenance_stale'); throw error; } return getTopicMaintenanceProposal(database, input.id)!; } database.exec('SAVEPOINT topic_maintenance_apply'); try { executeFrozen(database, { ...proposal, snapshot: { ...proposal.snapshot, frozenAt: now } }); database.prepare("UPDATE topic_maintenance_proposals SET status='approved',revision=revision+1,updated_at=?,decided_at=? WHERE id=?").run(now, now, input.id); database.exec('RELEASE topic_maintenance_apply'); } catch (error) { database.exec('ROLLBACK TO topic_maintenance_apply'); database.exec('RELEASE topic_maintenance_apply'); throw error; } return getTopicMaintenanceProposal(database, input.id)!; }
