import type { BrowserProfile } from '../main/browser-config';
import type { IntelligenceChannelsSummary } from '../main/intelligence-channels';
import type { WorkspaceBrowserBinding } from '../main/workspace-browser-binding';
import type { OwnerBrowserState } from '../main/browser-profile-owner';
import type { RoleModelCandidate, RoleModelThinkingLevel } from '../shared/pi-config';

export type WmbRoleId = 'desk' | 'reporter' | 'planner' | 'writer' | 'librarian';
export type WmbRoleModelCandidate = RoleModelCandidate;
export type WmbRoleModelThinkingLevel = RoleModelThinkingLevel;
export type WmbRoleModelPolicy = { candidates: WmbRoleModelCandidate[] };
export type WmbPiProfile = {
  id: string;
  name: string;
  baseUrl: string;
  model: string;
  api: 'openai-responses' | 'openai-completions' | 'anthropic-messages';
  authMode: 'bearer' | 'x-api-key' | 'none';
  credentialSourceKind: 'encrypted' | 'environment' | 'command' | 'none';
  credentialSourceLabel: string;
  capabilities: { text: boolean; vision: boolean; imageGeneration: boolean; nativeSearch: boolean; jsonOutput: boolean; streaming: boolean; modelIdDiscovery: boolean };
  health: { state: 'unknown' | 'healthy' | 'unhealthy'; lastProbeAt?: string; lastError?: string };
  thinking?: 'off' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max';
  contextWindow?: number;
  maxTokens?: number;
  configured: boolean;
  active: boolean;
};
export type WmbSettingsSnapshot = {
  paths: Record<string, string>;
  usage: Record<string, number>;
  counts: Record<string, number>;
  health: Record<string, unknown>;
  mcp: { status: string; url: string | null };
  browser: { status: string; pid?: number; cdpUrl?: string; profilePath?: string; mode?: 'quiet' | 'visible' | 'headless' };
  browserProfiles: BrowserProfile[];
  defaultBrowserProfileId: string;
  browserRegistryRevision: number;
  browserBinding: WorkspaceBrowserBinding | null;
  boundBrowserProfile: BrowserProfile | null;
  legacyBrowserSource: OwnerBrowserState['legacySource'];
  pi: {
    version: 4;
    activeId: string | null;
    profiles: WmbPiProfile[];
    baseUrl: string;
    model: string;
    configured: boolean;
    modelPolicyRevision: number;
    roleModelPolicies: Record<WmbRoleId, WmbRoleModelPolicy>;
  };
  piRuntime: { version: string; root: string; source: 'bundled' | 'override'; previousVersion: string | null; stagingVersion: string | null };
  workspace: {
    id: string; displayName: string; rootPath: string;
    dataRoot: { workspaceId: string; path: string };
    profile: { profileId: string; revision: number; intelligencePackId: string; creationPackId: string; platforms: Array<'x' | 'xiaohongshu' | 'wechat' | 'zhihu'> };
    intelligenceChannels: IntelligenceChannelsSummary;
    browserProfileId: string | null;
    bindingRevision: number | null;
    state: WorkspaceBrowserBinding['state'] | 'missing';
    expectedAccountSnapshots: WorkspaceBrowserBinding['expectedAccountSnapshot'];
    capabilities: { xLists: true; aiIntelligence: boolean; fixedAiLists: boolean; rankings: boolean; sourceWire: boolean; publishingPlatforms: Array<'x' | 'xiaohongshu' | 'wechat' | 'zhihu'> };
  };
};
